# AUTO-GENERATED by tcms_ai_testgen.executor_real (execution DSL). Do not edit.
import time

import pytest
from cantools.database.errors import EncodeError
from tcms import protocol as proto
from tcms.parser import collect, count_frames
from tcms import faultlevel


def _encode(db, name, **signals):
    for sig in db.get_message_by_name(name).signals:
        signals.setdefault(sig.name, 0)
    return db.encode_message(name, signals)


def test_agent_draft(db):
    assert faultlevel.action_for("door_fault") == "derate"

